language: perl
perl:
    - "5.14"
    - "5.26"
    - "5.28"
sudo: false

matrix:
    include:

        - perl: "5.26"
          env:
            - TEST_YANCY_BACKEND=sqlite:/tmp/sqlite3.db
          addons:
            apt:
              packages:
                - sqlite3
                - libdbd-sqlite3-perl
          install:
            - sqlite3 /tmp/sqlite3.db < t/schema/sqlite.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install Mojo::SQLite

        - perl: "5.26"
          env:
            - TEST_YANCY_BACKEND=mysql://travis@localhost/test_yancy
            - TEST_ONLINE_MYSQL=mysql://travis@localhost/yancy_mysql_test
          services:
            - mysql
          addons:
            apt:
              packages:
                - libdbd-mysql-perl
          install:
            - mysql -u travis -e 'CREATE DATABASE yancy_mysql_test'
            - mysql -u travis -e 'CREATE DATABASE test_yancy'
            - mysql -u travis test_yancy < t/schema/mysql.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install DBD::mysql@4.046 Mojo::mysql

        - perl: "5.26"
          env:
            - TEST_YANCY_BACKEND=pg://postgres@localhost/test_yancy
            - TEST_ONLINE_PG=postgres://postgres@localhost/test_backend
          services:
            - postgresql
          addons:
            postgresql: "10"
          install:
            - psql -c 'create database test_backend;' -U postgres
            - psql -c 'create database test_yancy;' -U postgres
            - psql -U postgres test_yancy < t/schema/pg.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpanm -v DBD::Pg@3.8.1 Mojo::Pg

        - perl: "5.26"
          env:
            - "TEST_YANCY_BACKEND=dbic://Local::Schema/dbi:SQLite:/tmp/sqlite3.db"
          addons:
            apt:
              packages:
                - sqlite3
          install:
            - sqlite3 /tmp/sqlite3.db < t/schema/sqlite.sql
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install DBIx::Class DBD::SQLite SQL::Translator

        - perl: "5.26"
          env: COVERAGE=1

        - perl: "5.28"
          env:
            - TEST_YANCY_EXAMPLES=1
          install:
            - cpan-install --deps
            - cpan-install --coverage
            - cpan-install Mojo::SQLite Mojolicious::Plugin::PODViewer
            - cpan-install Mojolicious::Command::export
            - cpan-install DateTime DateTime::Event::Recurrence
            - cpan-install Mojolicious::Plugin::AutoReload Yancy::Backend::Static

        - perl: "5.28"
          env:
              - MOJO_NO_JSON_XS=1

    allow_failures:
        - env: COVERAGE=1

before_install:
    - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
    - source ~/travis-perl-helpers/init
    - build-perl
    - perl -V
    - build-dist
    - cd $BUILD_DIR

install:
    - cpan-install --deps
    - cpan-install --coverage

before_script:
    - coverage-setup

script:
    - perl Makefile.PL
    - make
    - prove -bv -j1 $(test-files) # keep it fixed order, non-parallel to avoid weird fails

after_success:
    - coverage-report
